# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'lightcmdrBjoZhn.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1698, 1184)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Triangular)
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionPower = QAction(MainWindow)
        self.actionPower.setObjectName(u"actionPower")
        self.actionSetup = QAction(MainWindow)
        self.actionSetup.setObjectName(u"actionSetup")
        self.actionSwitching = QAction(MainWindow)
        self.actionSwitching.setObjectName(u"actionSwitching")
        self.actionData = QAction(MainWindow)
        self.actionData.setObjectName(u"actionData")
        self.actionNetwork = QAction(MainWindow)
        self.actionNetwork.setObjectName(u"actionNetwork")
        self.actionAdd = QAction(MainWindow)
        self.actionAdd.setObjectName(u"actionAdd")
        self.actionRemove = QAction(MainWindow)
        self.actionRemove.setObjectName(u"actionRemove")
        self.actionReorder = QAction(MainWindow)
        self.actionReorder.setObjectName(u"actionReorder")
        self.actionTransfer = QAction(MainWindow)
        self.actionTransfer.setObjectName(u"actionTransfer")
        self.actionSequence = QAction(MainWindow)
        self.actionSequence.setObjectName(u"actionSequence")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionImage = QAction(MainWindow)
        self.actionImage.setObjectName(u"actionImage")
        self.actionVideo = QAction(MainWindow)
        self.actionVideo.setObjectName(u"actionVideo")
        self.actionRT1 = QAction(MainWindow)
        self.actionRT1.setObjectName(u"actionRT1")
        self.actionOpenGL = QAction(MainWindow)
        self.actionOpenGL.setObjectName(u"actionOpenGL")
        self.actionOpen_File = QAction(MainWindow)
        self.actionOpen_File.setObjectName(u"actionOpen_File")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 10, 1466, 1411))
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.Visual = QWidget()
        self.Visual.setObjectName(u"Visual")
        self.vis_opengl = QOpenGLWidget(self.Visual)
        self.vis_opengl.setObjectName(u"vis_opengl")
        self.vis_opengl.setGeometry(QRect(10, 10, 1441, 961))
        self.camera_location_box = QComboBox(self.Visual)
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.addItem("")
        self.camera_location_box.setObjectName(u"camera_location_box")
        self.camera_location_box.setGeometry(QRect(550, 980, 191, 22))
        self.label_3 = QLabel(self.Visual)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(480, 980, 61, 20))
        self.res_abrt_can_buttonBox = QDialogButtonBox(self.Visual)
        self.res_abrt_can_buttonBox.setObjectName(u"res_abrt_can_buttonBox")
        self.res_abrt_can_buttonBox.setGeometry(QRect(190, 980, 156, 23))
        self.res_abrt_can_buttonBox.setStandardButtons(QDialogButtonBox.Abort|QDialogButtonBox.Cancel|QDialogButtonBox.Reset)
        self.vis_play = QPushButton(self.Visual)
        self.vis_play.setObjectName(u"vis_play")
        self.vis_play.setGeometry(QRect(10, 980, 75, 23))
        self.vis_pause = QPushButton(self.Visual)
        self.vis_pause.setObjectName(u"vis_pause")
        self.vis_pause.setGeometry(QRect(80, 980, 75, 23))
        self.audio_sel_box = QComboBox(self.Visual)
        self.audio_sel_box.setObjectName(u"audio_sel_box")
        self.audio_sel_box.setGeometry(QRect(10, 1020, 331, 22))
        self.label_7 = QLabel(self.Visual)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 1020, 47, 21))
        self.tabWidget.addTab(self.Visual, "")
        self.Sequence = QWidget()
        self.Sequence.setObjectName(u"Sequence")
        self.sequence_tree = QTreeWidget(self.Sequence)
        self.sequence_tree.setObjectName(u"sequence_tree")
        self.sequence_tree.setGeometry(QRect(170, 120, 256, 491))
        self.settings_seq = QToolButton(self.Sequence)
        self.settings_seq.setObjectName(u"settings_seq")
        self.settings_seq.setGeometry(QRect(170, 620, 25, 19))
        self.obj_seq_list = QListWidget(self.Sequence)
        self.obj_seq_list.setObjectName(u"obj_seq_list")
        self.obj_seq_list.setGeometry(QRect(170, 650, 256, 192))
        self.tx_seq_spin_double = QDoubleSpinBox(self.Sequence)
        self.tx_seq_spin_double.setObjectName(u"tx_seq_spin_double")
        self.tx_seq_spin_double.setGeometry(QRect(200, 620, 62, 22))
        self.spinBox = QSpinBox(self.Sequence)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(380, 620, 42, 22))
        self.toolBox_seq = QToolBox(self.Sequence)
        self.toolBox_seq.setObjectName(u"toolBox_seq")
        self.toolBox_seq.setGeometry(QRect(460, 380, 261, 461))
        self.light = QWidget()
        self.light.setObjectName(u"light")
        self.light.setGeometry(QRect(0, 0, 261, 326))
        self.lighton = QPushButton(self.light)
        self.lighton.setObjectName(u"lighton")
        self.lighton.setGeometry(QRect(0, 0, 261, 23))
        self.lightoff = QPushButton(self.light)
        self.lightoff.setObjectName(u"lightoff")
        self.lightoff.setGeometry(QRect(0, 20, 261, 23))
        self.toolBox_seq.addItem(self.light, u"Light")
        self.transitions = QWidget()
        self.transitions.setObjectName(u"transitions")
        self.transitions.setGeometry(QRect(0, 0, 261, 376))
        self.direct = QPushButton(self.transitions)
        self.direct.setObjectName(u"direct")
        self.direct.setGeometry(QRect(0, 0, 261, 23))
        self.smooth = QPushButton(self.transitions)
        self.smooth.setObjectName(u"smooth")
        self.smooth.setGeometry(QRect(0, 20, 261, 23))
        self.toolBox_seq.addItem(self.transitions, u"Transitions")
        self.colors = QWidget()
        self.colors.setObjectName(u"colors")
        self.colors.setGeometry(QRect(0, 0, 261, 376))
        self.color = QPushButton(self.colors)
        self.color.setObjectName(u"color")
        self.color.setGeometry(QRect(0, 0, 261, 23))
        self.huesweep = QPushButton(self.colors)
        self.huesweep.setObjectName(u"huesweep")
        self.huesweep.setGeometry(QRect(0, 20, 261, 23))
        self.colorpulse = QPushButton(self.colors)
        self.colorpulse.setObjectName(u"colorpulse")
        self.colorpulse.setGeometry(QRect(0, 40, 261, 23))
        self.colorsweep = QPushButton(self.colors)
        self.colorsweep.setObjectName(u"colorsweep")
        self.colorsweep.setGeometry(QRect(0, 60, 261, 23))
        self.toolBox_seq.addItem(self.colors, u"Colors")
        self.fadin_out = QWidget()
        self.fadin_out.setObjectName(u"fadin_out")
        self.fadin_out.setGeometry(QRect(0, 0, 261, 376))
        self.fadeover = QPushButton(self.fadin_out)
        self.fadeover.setObjectName(u"fadeover")
        self.fadeover.setGeometry(QRect(0, 0, 261, 23))
        self.fadefromblack = QPushButton(self.fadin_out)
        self.fadefromblack.setObjectName(u"fadefromblack")
        self.fadefromblack.setGeometry(QRect(0, 20, 261, 23))
        self.fadetoblack = QPushButton(self.fadin_out)
        self.fadetoblack.setObjectName(u"fadetoblack")
        self.fadetoblack.setGeometry(QRect(0, 40, 261, 23))
        self.toolBox_seq.addItem(self.fadin_out, u"Fade In/Out")
        self.animations = QWidget()
        self.animations.setObjectName(u"animations")
        self.animations.setGeometry(QRect(0, 0, 261, 376))
        self.flash = QPushButton(self.animations)
        self.flash.setObjectName(u"flash")
        self.flash.setGeometry(QRect(0, 0, 261, 23))
        self.linemotion = QPushButton(self.animations)
        self.linemotion.setObjectName(u"linemotion")
        self.linemotion.setGeometry(QRect(0, 20, 261, 23))
        self.linemotion_45 = QPushButton(self.animations)
        self.linemotion_45.setObjectName(u"linemotion_45")
        self.linemotion_45.setGeometry(QRect(0, 40, 261, 23))
        self.toolBox_seq.addItem(self.animations, u"Animations")
        self.seqAdd = QPushButton(self.Sequence)
        self.seqAdd.setObjectName(u"seqAdd")
        self.seqAdd.setGeometry(QRect(460, 90, 31, 23))
        self.seqAddAbove = QPushButton(self.Sequence)
        self.seqAddAbove.setObjectName(u"seqAddAbove")
        self.seqAddAbove.setGeometry(QRect(500, 90, 75, 23))
        self.seqAddBelow = QPushButton(self.Sequence)
        self.seqAddBelow.setObjectName(u"seqAddBelow")
        self.seqAddBelow.setGeometry(QRect(590, 90, 75, 23))
        self.seq_save = QPushButton(self.Sequence)
        self.seq_save.setObjectName(u"seq_save")
        self.seq_save.setGeometry(QRect(670, 90, 41, 23))
        self.seq_save_open = QDialogButtonBox(self.Sequence)
        self.seq_save_open.setObjectName(u"seq_save_open")
        self.seq_save_open.setGeometry(QRect(170, 60, 251, 23))
        self.seq_save_open.setStandardButtons(QDialogButtonBox.Open|QDialogButtonBox.RestoreDefaults|QDialogButtonBox.Save)
        self.moveup_seq = QPushButton(self.Sequence)
        self.moveup_seq.setObjectName(u"moveup_seq")
        self.moveup_seq.setGeometry(QRect(270, 620, 31, 23))
        self.movedown_seq = QPushButton(self.Sequence)
        self.movedown_seq.setObjectName(u"movedown_seq")
        self.movedown_seq.setGeometry(QRect(300, 620, 31, 23))
        self.pushButton_47 = QPushButton(self.Sequence)
        self.pushButton_47.setObjectName(u"pushButton_47")
        self.pushButton_47.setGeometry(QRect(390, 90, 31, 23))
        self.pushButton_48 = QPushButton(self.Sequence)
        self.pushButton_48.setObjectName(u"pushButton_48")
        self.pushButton_48.setGeometry(QRect(350, 90, 31, 23))
        self.plainTextEdit_seq = QPlainTextEdit(self.Sequence)
        self.plainTextEdit_seq.setObjectName(u"plainTextEdit_seq")
        self.plainTextEdit_seq.setGeometry(QRect(460, 120, 261, 201))
        self.comboBox_2 = QComboBox(self.Sequence)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(460, 345, 131, 22))
        self.label_47 = QLabel(self.Sequence)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(460, 330, 46, 16))
        self.tabWidget.addTab(self.Sequence, "")
        self.rack = QWidget()
        self.rack.setObjectName(u"rack")
        self.rack_opengl = QOpenGLWidget(self.rack)
        self.rack_opengl.setObjectName(u"rack_opengl")
        self.rack_opengl.setGeometry(QRect(180, 130, 241, 381))
        self.rackstack_list = QTreeWidget(self.rack)
        self.rackstack_list.setObjectName(u"rackstack_list")
        self.rackstack_list.setGeometry(QRect(180, 540, 241, 192))
        self.rackPartsBox = QToolBox(self.rack)
        self.rackPartsBox.setObjectName(u"rackPartsBox")
        self.rackPartsBox.setGeometry(QRect(440, 320, 221, 411))
        self.rackPartsBox.setFrameShape(QFrame.NoFrame)
        self.networking_box = QWidget()
        self.networking_box.setObjectName(u"networking_box")
        self.networking_box.setGeometry(QRect(0, 0, 221, 249))
        self._1u_24_patch = QPushButton(self.networking_box)
        self._1u_24_patch.setObjectName(u"_1u_24_patch")
        self._1u_24_patch.setGeometry(QRect(0, 0, 221, 23))
        self._2u_48_patch = QPushButton(self.networking_box)
        self._2u_48_patch.setObjectName(u"_2u_48_patch")
        self._2u_48_patch.setGeometry(QRect(0, 20, 221, 23))
        self._4u_96_patch = QPushButton(self.networking_box)
        self._4u_96_patch.setObjectName(u"_4u_96_patch")
        self._4u_96_patch.setGeometry(QRect(0, 40, 221, 23))
        self._1u_16pG_sw_M = QPushButton(self.networking_box)
        self._1u_16pG_sw_M.setObjectName(u"_1u_16pG_sw_M")
        self._1u_16pG_sw_M.setGeometry(QRect(0, 60, 221, 23))
        self._1u_24pG_sw_M = QPushButton(self.networking_box)
        self._1u_24pG_sw_M.setObjectName(u"_1u_24pG_sw_M")
        self._1u_24pG_sw_M.setGeometry(QRect(0, 80, 221, 23))
        self._1u_48pG_sw_M_sfp = QPushButton(self.networking_box)
        self._1u_48pG_sw_M_sfp.setObjectName(u"_1u_48pG_sw_M_sfp")
        self._1u_48pG_sw_M_sfp.setGeometry(QRect(0, 100, 221, 23))
        self._1u_48pG_sw_M_qsfp = QPushButton(self.networking_box)
        self._1u_48pG_sw_M_qsfp.setObjectName(u"_1u_48pG_sw_M_qsfp")
        self._1u_48pG_sw_M_qsfp.setGeometry(QRect(0, 120, 221, 23))
        self.rackPartsBox.addItem(self.networking_box, u"Networking")
        self.servers_box = QWidget()
        self.servers_box.setObjectName(u"servers_box")
        self.servers_box.setGeometry(QRect(0, 0, 100, 30))
        self._1u_base = QPushButton(self.servers_box)
        self._1u_base.setObjectName(u"_1u_base")
        self._1u_base.setGeometry(QRect(0, 0, 221, 23))
        self._2u_base = QPushButton(self.servers_box)
        self._2u_base.setObjectName(u"_2u_base")
        self._2u_base.setGeometry(QRect(0, 20, 221, 23))
        self._1u_avrx_960k_1 = QPushButton(self.servers_box)
        self._1u_avrx_960k_1.setObjectName(u"_1u_avrx_960k_1")
        self._1u_avrx_960k_1.setGeometry(QRect(0, 40, 221, 23))
        self._2u_avrx_960k_2u2 = QPushButton(self.servers_box)
        self._2u_avrx_960k_2u2.setObjectName(u"_2u_avrx_960k_2u2")
        self._2u_avrx_960k_2u2.setGeometry(QRect(0, 60, 221, 23))
        self.rackPartsBox.addItem(self.servers_box, u"Servers")
        self.controller_toolbox = QWidget()
        self.controller_toolbox.setObjectName(u"controller_toolbox")
        self.controller_toolbox.setGeometry(QRect(0, 0, 100, 30))
        self._2u_vk2_60c_light = QPushButton(self.controller_toolbox)
        self._2u_vk2_60c_light.setObjectName(u"_2u_vk2_60c_light")
        self._2u_vk2_60c_light.setGeometry(QRect(0, 0, 221, 23))
        self._2u_vk4_120c_light = QPushButton(self.controller_toolbox)
        self._2u_vk4_120c_light.setObjectName(u"_2u_vk4_120c_light")
        self._2u_vk4_120c_light.setGeometry(QRect(0, 20, 221, 23))
        self.rackPartsBox.addItem(self.controller_toolbox, u"Controllers")
        self.patch_box = QWidget()
        self.patch_box.setObjectName(u"patch_box")
        self.patch_box.setGeometry(QRect(0, 0, 100, 30))
        self._1u_24p_pan_empty_keystoneType = QPushButton(self.patch_box)
        self._1u_24p_pan_empty_keystoneType.setObjectName(u"_1u_24p_pan_empty_keystoneType")
        self._1u_24p_pan_empty_keystoneType.setGeometry(QRect(0, 0, 221, 23))
        self._keystone_rj45 = QPushButton(self.patch_box)
        self._keystone_rj45.setObjectName(u"_keystone_rj45")
        self._keystone_rj45.setGeometry(QRect(0, 20, 221, 23))
        self._keystone_xlr = QPushButton(self.patch_box)
        self._keystone_xlr.setObjectName(u"_keystone_xlr")
        self._keystone_xlr.setGeometry(QRect(0, 40, 221, 23))
        self._keystone_midi = QPushButton(self.patch_box)
        self._keystone_midi.setObjectName(u"_keystone_midi")
        self._keystone_midi.setGeometry(QRect(0, 60, 221, 23))
        self._keystone_toslink = QPushButton(self.patch_box)
        self._keystone_toslink.setObjectName(u"_keystone_toslink")
        self._keystone_toslink.setGeometry(QRect(0, 80, 221, 23))
        self._keystone_coax_bnc = QPushButton(self.patch_box)
        self._keystone_coax_bnc.setObjectName(u"_keystone_coax_bnc")
        self._keystone_coax_bnc.setGeometry(QRect(0, 100, 221, 23))
        self.rackPartsBox.addItem(self.patch_box, u"Patch")
        self.frame_page = QWidget()
        self.frame_page.setObjectName(u"frame_page")
        self.frame_page.setGeometry(QRect(0, 0, 100, 30))
        self._12u4pO = QPushButton(self.frame_page)
        self._12u4pO.setObjectName(u"_12u4pO")
        self._12u4pO.setGeometry(QRect(0, 20, 221, 23))
        self._9u4pO = QPushButton(self.frame_page)
        self._9u4pO.setObjectName(u"_9u4pO")
        self._9u4pO.setGeometry(QRect(0, 0, 221, 23))
        self._24u4pO = QPushButton(self.frame_page)
        self._24u4pO.setObjectName(u"_24u4pO")
        self._24u4pO.setGeometry(QRect(0, 40, 221, 23))
        self._48uCD_Hammond = QPushButton(self.frame_page)
        self._48uCD_Hammond.setObjectName(u"_48uCD_Hammond")
        self._48uCD_Hammond.setGeometry(QRect(0, 60, 221, 23))
        self.rackPartsBox.addItem(self.frame_page, u"Frame")
        self.amplifiers = QWidget()
        self.amplifiers.setObjectName(u"amplifiers")
        self.amplifiers.setGeometry(QRect(0, 0, 100, 30))
        self.RcfXps16K = QPushButton(self.amplifiers)
        self.RcfXps16K.setObjectName(u"RcfXps16K")
        self.RcfXps16K.setGeometry(QRect(0, 0, 221, 23))
        self.rackPartsBox.addItem(self.amplifiers, u"Amplifiers")
        self.rackSave = QPushButton(self.rack)
        self.rackSave.setObjectName(u"rackSave")
        self.rackSave.setGeometry(QRect(100, 130, 75, 23))
        self.rackLoad = QPushButton(self.rack)
        self.rackLoad.setObjectName(u"rackLoad")
        self.rackLoad.setGeometry(QRect(100, 150, 75, 23))
        self.label_4 = QLabel(self.rack)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(180, 110, 81, 16))
        self.label_5 = QLabel(self.rack)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(440, 110, 61, 16))
        self.label_6 = QLabel(self.rack)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(180, 520, 47, 13))
        self.rackUndo = QPushButton(self.rack)
        self.rackUndo.setObjectName(u"rackUndo")
        self.rackUndo.setGeometry(QRect(100, 240, 75, 23))
        self.rackRedo = QPushButton(self.rack)
        self.rackRedo.setObjectName(u"rackRedo")
        self.rackRedo.setGeometry(QRect(100, 260, 75, 23))
        self.rackpart_pte = QPlainTextEdit(self.rack)
        self.rackpart_pte.setObjectName(u"rackpart_pte")
        self.rackpart_pte.setGeometry(QRect(440, 130, 221, 171))
        self.treeView = QTreeView(self.rack)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(720, 130, 281, 346))
        self.label_19 = QLabel(self.rack)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(725, 110, 71, 16))
        self.pushButton = QPushButton(self.rack)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(105, 345, 31, 23))
        self.pushButton_2 = QPushButton(self.rack)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(135, 345, 31, 23))
        self.label_20 = QLabel(self.rack)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(110, 330, 47, 13))
        self.pushButton_3 = QPushButton(self.rack)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(105, 370, 61, 23))
        self.label_21 = QLabel(self.rack)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(105, 110, 47, 13))
        self.label_22 = QLabel(self.rack)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(105, 225, 47, 13))
        self.checkBox = QCheckBox(self.rack)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(370, 110, 70, 17))
        self.tabWidget.addTab(self.rack, "")
        self.audio = QWidget()
        self.audio.setObjectName(u"audio")
        self.audio_view = QOpenGLWidget(self.audio)
        self.audio_view.setObjectName(u"audio_view")
        self.audio_view.setGeometry(QRect(100, 90, 711, 151))
        self.positionAudioBar = QScrollBar(self.audio)
        self.positionAudioBar.setObjectName(u"positionAudioBar")
        self.positionAudioBar.setGeometry(QRect(100, 240, 711, 16))
        self.positionAudioBar.setOrientation(Qt.Horizontal)
        self.gainScrollBar = QScrollBar(self.audio)
        self.gainScrollBar.setObjectName(u"gainScrollBar")
        self.gainScrollBar.setGeometry(QRect(80, 90, 16, 160))
        self.gainScrollBar.setOrientation(Qt.Vertical)
        self.audioLoad_btn = QPushButton(self.audio)
        self.audioLoad_btn.setObjectName(u"audioLoad_btn")
        self.audioLoad_btn.setGeometry(QRect(100, 60, 75, 23))
        self.move_left = QPushButton(self.audio)
        self.move_left.setObjectName(u"move_left")
        self.move_left.setGeometry(QRect(100, 260, 21, 23))
        self.move_right = QPushButton(self.audio)
        self.move_right.setObjectName(u"move_right")
        self.move_right.setGeometry(QRect(130, 260, 21, 23))
        self.groupBox = QGroupBox(self.audio)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(100, 310, 321, 261))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 20, 21, 16))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(100, 20, 21, 16))
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 40, 16, 21))
        self.line = QFrame(self.groupBox)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 30, 191, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.groupBox)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 20, 20, 111))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.groupBox)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(70, 20, 20, 111))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 100, 16, 16))
        self.gain_spinbox_double = QDoubleSpinBox(self.groupBox)
        self.gain_spinbox_double.setObjectName(u"gain_spinbox_double")
        self.gain_spinbox_double.setGeometry(QRect(20, 140, 61, 22))
        self.pan_spinbox = QSpinBox(self.groupBox)
        self.pan_spinbox.setObjectName(u"pan_spinbox")
        self.pan_spinbox.setGeometry(QRect(90, 140, 42, 22))
        self.c_gain = QDial(self.groupBox)
        self.c_gain.setObjectName(u"c_gain")
        self.c_gain.setGeometry(QRect(30, 30, 41, 51))
        self.c_gain.setMaximum(100)
        self.c_gain.setValue(20)
        self.c_gain.setInvertedAppearance(False)
        self.c_gain.setInvertedControls(False)
        self.c_gain.setNotchesVisible(True)
        self.o_gain = QDial(self.groupBox)
        self.o_gain.setObjectName(u"o_gain")
        self.o_gain.setGeometry(QRect(30, 80, 41, 51))
        self.o_gain.setMaximum(100)
        self.o_gain.setValue(20)
        self.o_gain.setNotchTarget(3.700000000000000)
        self.o_gain.setNotchesVisible(True)
        self.c_pan = QDial(self.groupBox)
        self.c_pan.setObjectName(u"c_pan")
        self.c_pan.setGeometry(QRect(90, 30, 41, 51))
        self.c_pan.setMaximum(100)
        self.c_pan.setValue(50)
        self.c_pan.setNotchTarget(10.699999999999999)
        self.c_pan.setNotchesVisible(True)
        self.o_pan = QDial(self.groupBox)
        self.o_pan.setObjectName(u"o_pan")
        self.o_pan.setGeometry(QRect(90, 80, 41, 51))
        self.o_pan.setMaximum(100)
        self.o_pan.setValue(50)
        self.o_pan.setNotchTarget(10.699999999999999)
        self.o_pan.setNotchesVisible(True)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(90, 70, 47, 13))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(90, 120, 47, 13))
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 70, 51, 20))
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 120, 51, 20))
        self.r_audio_montor_bar = QProgressBar(self.groupBox)
        self.r_audio_montor_bar.setObjectName(u"r_audio_montor_bar")
        self.r_audio_montor_bar.setGeometry(QRect(240, 40, 21, 71))
        self.r_audio_montor_bar.setValue(20)
        self.r_audio_montor_bar.setTextVisible(False)
        self.r_audio_montor_bar.setOrientation(Qt.Vertical)
        self.r_audio_montor_bar.setInvertedAppearance(False)
        self.r_audio_montor_bar.setTextDirection(QProgressBar.TopToBottom)
        self.l_audio_monitor_bar = QProgressBar(self.groupBox)
        self.l_audio_monitor_bar.setObjectName(u"l_audio_monitor_bar")
        self.l_audio_monitor_bar.setGeometry(QRect(270, 40, 21, 71))
        self.l_audio_monitor_bar.setValue(20)
        self.l_audio_monitor_bar.setOrientation(Qt.Vertical)
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(250, 20, 47, 13))
        self.mon_gain = QDial(self.groupBox)
        self.mon_gain.setObjectName(u"mon_gain")
        self.mon_gain.setGeometry(QRect(240, 120, 31, 31))
        self.mon_gain.setMaximum(100)
        self.mon_gain.setValue(20)
        self.mon_gain.setInvertedAppearance(False)
        self.mon_gain.setInvertedControls(False)
        self.mon_gain.setNotchesVisible(True)
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(230, 140, 51, 20))
        self.mon_pan = QDial(self.groupBox)
        self.mon_pan.setObjectName(u"mon_pan")
        self.mon_pan.setGeometry(QRect(240, 160, 31, 41))
        self.mon_pan.setMaximum(100)
        self.mon_pan.setValue(50)
        self.mon_pan.setNotchTarget(10.699999999999999)
        self.mon_pan.setNotchesVisible(True)
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(240, 190, 47, 13))
        self.verticalSlider = QSlider(self.groupBox)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(150, 95, 22, 160))
        self.verticalSlider.setSliderPosition(79)
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.verticalSlider.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider.setTickInterval(0)
        self.verticalSlider_2 = QSlider(self.groupBox)
        self.verticalSlider_2.setObjectName(u"verticalSlider_2")
        self.verticalSlider_2.setGeometry(QRect(190, 95, 22, 160))
        self.verticalSlider_2.setSliderPosition(79)
        self.verticalSlider_2.setOrientation(Qt.Vertical)
        self.verticalSlider_2.setTickPosition(QSlider.TicksBelow)
        self.label_27 = QLabel(self.groupBox)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(160, 70, 66, 16))
        self.label_28 = QLabel(self.groupBox)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(160, 55, 51, 16))
        self.label_29 = QLabel(self.groupBox)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(180, 125, 47, 13))
        self.label_30 = QLabel(self.groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(175, 100, 47, 13))
        self.label_31 = QLabel(self.groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(170, 245, 47, 13))
        self.label_32 = QLabel(self.groupBox)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(175, 150, 47, 13))
        self.label_33 = QLabel(self.groupBox)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(175, 175, 47, 13))
        self.label_34 = QLabel(self.groupBox)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(175, 200, 47, 13))
        self.label_35 = QLabel(self.groupBox)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(175, 225, 47, 13))
        self.groupBox_2 = QGroupBox(self.audio)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(430, 310, 181, 261))
        self.add_seqmarker = QPushButton(self.groupBox_2)
        self.add_seqmarker.setObjectName(u"add_seqmarker")
        self.add_seqmarker.setGeometry(QRect(10, 20, 75, 23))
        self.remove_seqmarker = QPushButton(self.groupBox_2)
        self.remove_seqmarker.setObjectName(u"remove_seqmarker")
        self.remove_seqmarker.setGeometry(QRect(10, 40, 75, 23))
        self.undoseqmarkeraction = QPushButton(self.groupBox_2)
        self.undoseqmarkeraction.setObjectName(u"undoseqmarkeraction")
        self.undoseqmarkeraction.setGeometry(QRect(10, 60, 75, 23))
        self.groupBox_3 = QGroupBox(self.audio)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(620, 310, 120, 141))
        self.comboBox = QComboBox(self.groupBox_3)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 20, 101, 22))
        self.checkBox_2 = QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 50, 101, 17))
        self.pushButton_4 = QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(10, 75, 75, 23))
        self.groupBox_4 = QGroupBox(self.audio)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(100, 570, 311, 221))
        self.treeWidget = QTreeWidget(self.groupBox_4)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(195, 15, 106, 86))
        self.listWidget = QListWidget(self.groupBox_4)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(195, 110, 106, 101))
        self.pushButton_5 = QPushButton(self.groupBox_4)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(5, 20, 75, 23))
        self.pushButton_6 = QPushButton(self.groupBox_4)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(5, 60, 75, 23))
        self.pushButton_7 = QPushButton(self.groupBox_4)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(5, 80, 75, 23))
        self.tabWidget.addTab(self.audio, "")
        self.setup = QWidget()
        self.setup.setObjectName(u"setup")
        self.groupBox_5 = QGroupBox(self.setup)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(100, 75, 376, 226))
        self.lineEdit = QLineEdit(self.groupBox_5)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 35, 156, 20))
        self.label_23 = QLabel(self.groupBox_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 20, 76, 16))
        self.label_24 = QLabel(self.groupBox_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 75, 121, 16))
        self.lineEdit_2 = QLineEdit(self.groupBox_5)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 95, 156, 20))
        self.groupBox_6 = QGroupBox(self.setup)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(485, 75, 551, 226))
        self.fontComboBox = QFontComboBox(self.groupBox_6)
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.fontComboBox.setGeometry(QRect(20, 35, 188, 22))
        self.label_36 = QLabel(self.groupBox_6)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(20, 20, 47, 13))
        self.label_37 = QLabel(self.groupBox_6)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(20, 95, 66, 16))
        self.spinBox_2 = QSpinBox(self.groupBox_6)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(20, 115, 81, 22))
        self.spinBox_2.setMaximum(100000)
        self.groupBox_7 = QGroupBox(self.setup)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(100, 305, 376, 406))
        self.tabWidget_2 = QTabWidget(self.groupBox_7)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(5, 15, 366, 386))
        self.installed_plug = QWidget()
        self.installed_plug.setObjectName(u"installed_plug")
        self.listWidget_2 = QListWidget(self.installed_plug)
        self.listWidget_2.setObjectName(u"listWidget_2")
        self.listWidget_2.setGeometry(QRect(0, 25, 356, 331))
        self.pushButton_9 = QPushButton(self.installed_plug)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(300, 0, 56, 23))
        self.lineEdit_3 = QLineEdit(self.installed_plug)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(25, 0, 271, 20))
        self.pushButton_10 = QPushButton(self.installed_plug)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(0, 0, 21, 23))
        self.tabWidget_2.addTab(self.installed_plug, "")
        self.marketplace_plug = QWidget()
        self.marketplace_plug.setObjectName(u"marketplace_plug")
        self.pushButton_8 = QPushButton(self.marketplace_plug)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(299, 0, 56, 23))
        self.lineEdit_4 = QLineEdit(self.marketplace_plug)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(25, 0, 271, 20))
        self.listWidget_3 = QListWidget(self.marketplace_plug)
        self.listWidget_3.setObjectName(u"listWidget_3")
        self.listWidget_3.setGeometry(QRect(0, 25, 356, 331))
        self.pushButton_11 = QPushButton(self.marketplace_plug)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(0, 0, 21, 23))
        self.tabWidget_2.addTab(self.marketplace_plug, "")
        self.groupBox_8 = QGroupBox(self.setup)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(485, 305, 551, 406))
        self.label_25 = QLabel(self.groupBox_8)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 30, 61, 16))
        self.label_26 = QLabel(self.groupBox_8)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(330, 30, 61, 16))
        self.timeEdit = QTimeEdit(self.groupBox_8)
        self.timeEdit.setObjectName(u"timeEdit")
        self.timeEdit.setGeometry(QRect(330, 50, 118, 22))
        self.calendarWidget = QCalendarWidget(self.groupBox_8)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(10, 50, 306, 186))
        self.groupBox_9 = QGroupBox(self.setup)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(100, 715, 936, 341))
        self.tabWidget_3 = QTabWidget(self.groupBox_9)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(5, 20, 366, 316))
        self.installed_plug_2 = QWidget()
        self.installed_plug_2.setObjectName(u"installed_plug_2")
        self.listWidget_4 = QListWidget(self.installed_plug_2)
        self.listWidget_4.setObjectName(u"listWidget_4")
        self.listWidget_4.setGeometry(QRect(0, 25, 356, 261))
        self.pushButton_12 = QPushButton(self.installed_plug_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(300, 0, 56, 23))
        self.lineEdit_5 = QLineEdit(self.installed_plug_2)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(45, 0, 251, 20))
        self.pushButton_13 = QPushButton(self.installed_plug_2)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(0, 0, 21, 23))
        self.pushButton_16 = QPushButton(self.installed_plug_2)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(20, 0, 21, 23))
        self.tabWidget_3.addTab(self.installed_plug_2, "")
        self.marketplace_plug_2 = QWidget()
        self.marketplace_plug_2.setObjectName(u"marketplace_plug_2")
        self.pushButton_14 = QPushButton(self.marketplace_plug_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(299, 0, 56, 23))
        self.lineEdit_6 = QLineEdit(self.marketplace_plug_2)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(25, 0, 271, 20))
        self.listWidget_5 = QListWidget(self.marketplace_plug_2)
        self.listWidget_5.setObjectName(u"listWidget_5")
        self.listWidget_5.setGeometry(QRect(0, 25, 356, 261))
        self.pushButton_15 = QPushButton(self.marketplace_plug_2)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(0, 0, 21, 23))
        self.tabWidget_3.addTab(self.marketplace_plug_2, "")
        self.label_38 = QLabel(self.groupBox_9)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(415, 25, 61, 16))
        self.timeEdit_2 = QTimeEdit(self.groupBox_9)
        self.timeEdit_2.setObjectName(u"timeEdit_2")
        self.timeEdit_2.setGeometry(QRect(415, 40, 118, 22))
        self.label_39 = QLabel(self.groupBox_9)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(415, 85, 47, 13))
        self.lineEdit_7 = QLineEdit(self.groupBox_9)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(415, 100, 113, 20))
        self.groupBox_10 = QGroupBox(self.groupBox_9)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(550, 25, 376, 306))
        self.label_40 = QLabel(self.groupBox_10)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 30, 96, 16))
        self.label_41 = QLabel(self.groupBox_10)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 70, 106, 16))
        self.label_42 = QLabel(self.groupBox_10)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(185, 30, 96, 16))
        self.label_43 = QLabel(self.groupBox_10)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(185, 70, 96, 16))
        self.label_44 = QLabel(self.groupBox_10)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(185, 110, 96, 16))
        self.label_45 = QLabel(self.groupBox_10)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(185, 150, 96, 16))
        self.label_46 = QLabel(self.groupBox_10)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(185, 190, 96, 16))
        self.line_4 = QFrame(self.groupBox_10)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(170, 25, 16, 206))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(self.groupBox_10)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(110, 30, 61, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.spinBox_3 = QSpinBox(self.groupBox_10)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(10, 45, 96, 22))
        self.spinBox_4 = QSpinBox(self.groupBox_10)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(10, 90, 96, 22))
        self.spinBox_5 = QSpinBox(self.groupBox_10)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(185, 45, 96, 22))
        self.spinBox_6 = QSpinBox(self.groupBox_10)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(185, 85, 96, 22))
        self.spinBox_7 = QSpinBox(self.groupBox_10)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(185, 125, 96, 22))
        self.spinBox_8 = QSpinBox(self.groupBox_10)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setGeometry(QRect(185, 165, 96, 22))
        self.spinBox_9 = QSpinBox(self.groupBox_10)
        self.spinBox_9.setObjectName(u"spinBox_9")
        self.spinBox_9.setGeometry(QRect(185, 205, 96, 22))
        self.buttonBox = QDialogButtonBox(self.groupBox_9)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(380, 295, 156, 46))
        self.buttonBox.setStandardButtons(QDialogButtonBox.Apply|QDialogButtonBox.Discard|QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.tabWidget.addTab(self.setup, "")
        self.tx_progress = QProgressBar(self.centralwidget)
        self.tx_progress.setObjectName(u"tx_progress")
        self.tx_progress.setGeometry(QRect(1580, 0, 118, 23))
        self.tx_progress.setAutoFillBackground(False)
        self.tx_progress.setValue(0)
        self.tx_progress.setTextVisible(True)
        self.tx_progress.setInvertedAppearance(False)
        self.tx_number_stat = QLCDNumber(self.centralwidget)
        self.tx_number_stat.setObjectName(u"tx_number_stat")
        self.tx_number_stat.setGeometry(QRect(1520, 0, 61, 21))
        self.tx_number_stat.setDigitCount(4)
        self.sources_view = QTreeView(self.centralwidget)
        self.sources_view.setObjectName(u"sources_view")
        self.sources_view.setGeometry(QRect(1470, 650, 221, 351))
        font = QFont()
        font.setKerning(True)
        self.sources_view.setFont(font)
        self.sources_view.setAlternatingRowColors(True)
        self.sources_view.setSortingEnabled(True)
        self.current_sequence = QTreeWidget(self.centralwidget)
        self.current_sequence.setObjectName(u"current_sequence")
        self.current_sequence.setGeometry(QRect(1470, 300, 221, 241))
        self.current_sequence.setSortingEnabled(True)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1470, 270, 91, 31))
        self.label.setTextFormat(Qt.MarkdownText)
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1470, 630, 47, 13))
        self.doubleSpinBox = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(1525, 30, 62, 22))
        self.toolButton = QToolButton(self.centralwidget)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(1665, 630, 25, 19))
        self.toolButton_2 = QToolButton(self.centralwidget)
        self.toolButton_2.setObjectName(u"toolButton_2")
        self.toolButton_2.setGeometry(QRect(1445, 5, 25, 19))
        MainWindow.setCentralWidget(self.centralwidget)
        self.tx_progress.raise_()
        self.tx_number_stat.raise_()
        self.tabWidget.raise_()
        self.sources_view.raise_()
        self.current_sequence.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.doubleSpinBox.raise_()
        self.toolButton.raise_()
        self.toolButton_2.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1698, 21))
        self.menuVisual = QMenu(self.menubar)
        self.menuVisual.setObjectName(u"menuVisual")
        self.menuRender = QMenu(self.menuVisual)
        self.menuRender.setObjectName(u"menuRender")
        self.menuDisplay = QMenu(self.menuVisual)
        self.menuDisplay.setObjectName(u"menuDisplay")
        self.menuSchedule = QMenu(self.menubar)
        self.menuSchedule.setObjectName(u"menuSchedule")
        self.menuSchedule.setGeometry(QRect(332, 130, 135, 169))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuSchedule.sizePolicy().hasHeightForWidth())
        self.menuSchedule.setSizePolicy(sizePolicy)
        self.menuRack = QMenu(self.menubar)
        self.menuRack.setObjectName(u"menuRack")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuAudio = QMenu(self.menubar)
        self.menuAudio.setObjectName(u"menuAudio")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuVisual.menuAction())
        self.menubar.addAction(self.menuSchedule.menuAction())
        self.menubar.addAction(self.menuRack.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAudio.menuAction())
        self.menuVisual.addAction(self.menuRender.menuAction())
        self.menuVisual.addAction(self.menuDisplay.menuAction())
        self.menuRender.addAction(self.actionImage)
        self.menuRender.addAction(self.actionVideo)
        self.menuDisplay.addAction(self.actionRT1)
        self.menuDisplay.addAction(self.actionOpenGL)
        self.menuSchedule.addAction(self.actionAdd)
        self.menuSchedule.addAction(self.actionRemove)
        self.menuSchedule.addAction(self.actionReorder)
        self.menuSchedule.addSeparator()
        self.menuSchedule.addAction(self.actionTransfer)
        self.menuSchedule.addAction(self.actionSequence)
        self.menuRack.addAction(self.actionSettings)
        self.menuRack.addAction(self.actionPower)
        self.menuRack.addAction(self.actionSetup)
        self.menuRack.addAction(self.actionSwitching)
        self.menuRack.addAction(self.actionData)
        self.menuRack.addAction(self.actionNetwork)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuAudio.addAction(self.actionOpen_File)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(3)
        self.toolBox_seq.setCurrentIndex(0)
        self.rackPartsBox.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.actionPower.setText(QCoreApplication.translate("MainWindow", u"Power", None))
        self.actionSetup.setText(QCoreApplication.translate("MainWindow", u"Setup", None))
        self.actionSwitching.setText(QCoreApplication.translate("MainWindow", u"Switching", None))
        self.actionData.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        self.actionNetwork.setText(QCoreApplication.translate("MainWindow", u"Network", None))
        self.actionAdd.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.actionRemove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.actionReorder.setText(QCoreApplication.translate("MainWindow", u"Reorder", None))
        self.actionTransfer.setText(QCoreApplication.translate("MainWindow", u"Transfer", None))
        self.actionSequence.setText(QCoreApplication.translate("MainWindow", u"Sequence", None))
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
        self.actionImage.setText(QCoreApplication.translate("MainWindow", u"Image", None))
        self.actionVideo.setText(QCoreApplication.translate("MainWindow", u"Video", None))
        self.actionRT1.setText(QCoreApplication.translate("MainWindow", u"RT1", None))
        self.actionOpenGL.setText(QCoreApplication.translate("MainWindow", u"OpenGL", None))
        self.actionOpen_File.setText(QCoreApplication.translate("MainWindow", u"Open File..", None))
        self.camera_location_box.setItemText(0, QCoreApplication.translate("MainWindow", u"N-AIR", None))
        self.camera_location_box.setItemText(1, QCoreApplication.translate("MainWindow", u"NE-AIR", None))
        self.camera_location_box.setItemText(2, QCoreApplication.translate("MainWindow", u"E-AIR", None))
        self.camera_location_box.setItemText(3, QCoreApplication.translate("MainWindow", u"SE-AIR", None))
        self.camera_location_box.setItemText(4, QCoreApplication.translate("MainWindow", u"S-AIR", None))
        self.camera_location_box.setItemText(5, QCoreApplication.translate("MainWindow", u"SW-AIR", None))
        self.camera_location_box.setItemText(6, QCoreApplication.translate("MainWindow", u"W-AIR", None))
        self.camera_location_box.setItemText(7, QCoreApplication.translate("MainWindow", u"NW-AIR", None))
        self.camera_location_box.setItemText(8, QCoreApplication.translate("MainWindow", u"N-GROUND", None))
        self.camera_location_box.setItemText(9, QCoreApplication.translate("MainWindow", u"NE-GROUND", None))
        self.camera_location_box.setItemText(10, QCoreApplication.translate("MainWindow", u"E-GROUND", None))
        self.camera_location_box.setItemText(11, QCoreApplication.translate("MainWindow", u"SE-GROUND", None))
        self.camera_location_box.setItemText(12, QCoreApplication.translate("MainWindow", u"S-GROUND", None))
        self.camera_location_box.setItemText(13, QCoreApplication.translate("MainWindow", u"SW_GROUND", None))
        self.camera_location_box.setItemText(14, QCoreApplication.translate("MainWindow", u"W-GROUND", None))
        self.camera_location_box.setItemText(15, QCoreApplication.translate("MainWindow", u"NW-GROUND", None))

        self.camera_location_box.setCurrentText(QCoreApplication.translate("MainWindow", u"N-AIR", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Camera Loc.", None))
        self.vis_play.setText(QCoreApplication.translate("MainWindow", u"Play", None))
        self.vis_pause.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Audio File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visual), QCoreApplication.translate("MainWindow", u"Visual", None))
        ___qtreewidgetitem = self.sequence_tree.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"START::", None));
        self.settings_seq.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lighton.setText(QCoreApplication.translate("MainWindow", u"LightON", None))
        self.lightoff.setText(QCoreApplication.translate("MainWindow", u"LightOFF", None))
        self.toolBox_seq.setItemText(self.toolBox_seq.indexOf(self.light), QCoreApplication.translate("MainWindow", u"Light", None))
        self.direct.setText(QCoreApplication.translate("MainWindow", u"Direct", None))
        self.smooth.setText(QCoreApplication.translate("MainWindow", u"Smooth", None))
        self.toolBox_seq.setItemText(self.toolBox_seq.indexOf(self.transitions), QCoreApplication.translate("MainWindow", u"Transitions", None))
        self.color.setText(QCoreApplication.translate("MainWindow", u"Color", None))
        self.huesweep.setText(QCoreApplication.translate("MainWindow", u"HueSweep", None))
        self.colorpulse.setText(QCoreApplication.translate("MainWindow", u"ColorPulse", None))
        self.colorsweep.setText(QCoreApplication.translate("MainWindow", u"ColorSweep", None))
        self.toolBox_seq.setItemText(self.toolBox_seq.indexOf(self.colors), QCoreApplication.translate("MainWindow", u"Colors", None))
        self.fadeover.setText(QCoreApplication.translate("MainWindow", u"Fadeover", None))
        self.fadefromblack.setText(QCoreApplication.translate("MainWindow", u"Fade From Black", None))
        self.fadetoblack.setText(QCoreApplication.translate("MainWindow", u"Fade To Black", None))
        self.toolBox_seq.setItemText(self.toolBox_seq.indexOf(self.fadin_out), QCoreApplication.translate("MainWindow", u"Fade In/Out", None))
        self.flash.setText(QCoreApplication.translate("MainWindow", u"Flash", None))
        self.linemotion.setText(QCoreApplication.translate("MainWindow", u"LineMotion", None))
        self.linemotion_45.setText(QCoreApplication.translate("MainWindow", u"LineMotion_45", None))
        self.toolBox_seq.setItemText(self.toolBox_seq.indexOf(self.animations), QCoreApplication.translate("MainWindow", u"Animations", None))
        self.seqAdd.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.seqAddAbove.setText(QCoreApplication.translate("MainWindow", u"Add Above", None))
        self.seqAddBelow.setText(QCoreApplication.translate("MainWindow", u"Add Below", None))
        self.seq_save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.moveup_seq.setText(QCoreApplication.translate("MainWindow", u"/\\", None))
        self.movedown_seq.setText(QCoreApplication.translate("MainWindow", u"\\/", None))
        self.pushButton_47.setText(QCoreApplication.translate("MainWindow", u"\\/", None))
        self.pushButton_48.setText(QCoreApplication.translate("MainWindow", u"/\\", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Apply To:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sequence), QCoreApplication.translate("MainWindow", u"Sequence", None))
        ___qtreewidgetitem1 = self.rackstack_list.headerItem()
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"RACK::", None));
        self._1u_24_patch.setText(QCoreApplication.translate("MainWindow", u"1U 24 Port Patch Panel", None))
        self._2u_48_patch.setText(QCoreApplication.translate("MainWindow", u"2U 48 Port Patch Panel", None))
        self._4u_96_patch.setText(QCoreApplication.translate("MainWindow", u"4U 96 Port Patch Panel", None))
        self._1u_16pG_sw_M.setText(QCoreApplication.translate("MainWindow", u"1U 16 Port Gigabit Switch - Managed", None))
        self._1u_24pG_sw_M.setText(QCoreApplication.translate("MainWindow", u"1U 24 Port Gigabit Switch - Managed", None))
        self._1u_48pG_sw_M_sfp.setText(QCoreApplication.translate("MainWindow", u"1U 48 Port Gigabit Switch - Managed SFP", None))
        self._1u_48pG_sw_M_qsfp.setText(QCoreApplication.translate("MainWindow", u"1U 48 Port Gigabit Switch - Managed QSFP", None))
        self.rackPartsBox.setItemText(self.rackPartsBox.indexOf(self.networking_box), QCoreApplication.translate("MainWindow", u"Networking", None))
        self._1u_base.setText(QCoreApplication.translate("MainWindow", u"1U Basic", None))
        self._2u_base.setText(QCoreApplication.translate("MainWindow", u"2U Basic", None))
        self._1u_avrx_960k_1.setText(QCoreApplication.translate("MainWindow", u"1U AVRX 960K-1", None))
        self._2u_avrx_960k_2u2.setText(QCoreApplication.translate("MainWindow", u"2U AVRX 960K-2U2", None))
        self.rackPartsBox.setItemText(self.rackPartsBox.indexOf(self.servers_box), QCoreApplication.translate("MainWindow", u"Servers", None))
        self._2u_vk2_60c_light.setText(QCoreApplication.translate("MainWindow", u"2U VK2 60 Channel Light Controller", None))
        self._2u_vk4_120c_light.setText(QCoreApplication.translate("MainWindow", u"2U VK4 120 Channel Light Controller", None))
        self.rackPartsBox.setItemText(self.rackPartsBox.indexOf(self.controller_toolbox), QCoreApplication.translate("MainWindow", u"Controllers", None))
        self._1u_24p_pan_empty_keystoneType.setText(QCoreApplication.translate("MainWindow", u"1U 24 Port Patch Panel Empty Keystone", None))
        self._keystone_rj45.setText(QCoreApplication.translate("MainWindow", u"RJ45 Keystone", None))
        self._keystone_xlr.setText(QCoreApplication.translate("MainWindow", u"XLR Keystone", None))
        self._keystone_midi.setText(QCoreApplication.translate("MainWindow", u"MIDI Connector Keystone", None))
        self._keystone_toslink.setText(QCoreApplication.translate("MainWindow", u"TOSLINK Keystone", None))
        self._keystone_coax_bnc.setText(QCoreApplication.translate("MainWindow", u"BNC/COAX Keystone", None))
        self.rackPartsBox.setItemText(self.rackPartsBox.indexOf(self.patch_box), QCoreApplication.translate("MainWindow", u"Patch", None))
        self._12u4pO.setText(QCoreApplication.translate("MainWindow", u"12U FourPost Open", None))
        self._9u4pO.setText(QCoreApplication.translate("MainWindow", u"9U FourPost Open", None))
        self._24u4pO.setText(QCoreApplication.translate("MainWindow", u"24U FourPost Open", None))
        self._48uCD_Hammond.setText(QCoreApplication.translate("MainWindow", u"48U Closed_Doors_Hammond", None))
        self.rackPartsBox.setItemText(self.rackPartsBox.indexOf(self.frame_page), QCoreApplication.translate("MainWindow", u"Frame", None))
        self.RcfXps16K.setText(QCoreApplication.translate("MainWindow", u"RCF XPS 16k 4kW", None))
        self.rackPartsBox.setItemText(self.rackPartsBox.indexOf(self.amplifiers), QCoreApplication.translate("MainWindow", u"Amplifiers", None))
        self.rackSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.rackLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Rack Visualiation", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Current Unit", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Stack List", None))
        self.rackUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.rackRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Input/Output", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"UP", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"DN", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Position", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"File", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Action", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Lock", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rack), QCoreApplication.translate("MainWindow", u"Rack", None))
        self.audioLoad_btn.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.move_left.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.move_right.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Mixer", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Gain", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Pan", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"L           R", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"L           R", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u" -\u221e      +5", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u" -\u221e      +5", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Monitor", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u" -\u221e      +5", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"L       R", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"A          B", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Main MUX", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"+5", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u" -\u221e", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"-10", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"-20", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"-40", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"-80", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Sequencing", None))
        self.add_seqmarker.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.remove_seqmarker.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.undoseqmarkeraction.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Rack", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Low Power Mode", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Program", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Plugin", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"OK", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Disable", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.audio), QCoreApplication.translate("MainWindow", u"Audio", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Source", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Source Folder", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Current Setup Location", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"General Propreties", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Font", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Total Frames", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Plugins", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Uninstall", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\ud83d\udd0d", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.installed_plug), QCoreApplication.translate("MainWindow", u"Installed", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Install", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"\ud83d\udd0d", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.marketplace_plug), QCoreApplication.translate("MainWindow", u"Marketplace", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Event", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Event Date", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Event Time", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Location / Map", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"\ud83d\udd0d", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"\u21bb", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.installed_plug_2), QCoreApplication.translate("MainWindow", u"Installed", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"\ud83d\udd0d", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.marketplace_plug_2), QCoreApplication.translate("MainWindow", u"Marketplace", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Time of Day", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Weather", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Light Propreties", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Total # Controllable", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Total # Uncontrollable", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Total # RGB", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Total # W", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Total # UV", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Total # IR", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Total # LASER", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setup), QCoreApplication.translate("MainWindow", u"Setup", None))
        ___qtreewidgetitem2 = self.current_sequence.headerItem()
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"START::", None));
        self.label.setText(QCoreApplication.translate("MainWindow", u"Current Sequence", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Sources", None))
        self.toolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.menuVisual.setTitle(QCoreApplication.translate("MainWindow", u"Visual", None))
        self.menuRender.setTitle(QCoreApplication.translate("MainWindow", u"Render", None))
        self.menuDisplay.setTitle(QCoreApplication.translate("MainWindow", u"Display", None))
        self.menuSchedule.setTitle(QCoreApplication.translate("MainWindow", u"Schedule", None))
        self.menuRack.setTitle(QCoreApplication.translate("MainWindow", u"Rack", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuAudio.setTitle(QCoreApplication.translate("MainWindow", u"Audio", None))
    # retranslateUi

